# Generated by Django 3.2.12 on 2024-08-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendapp', '0002_auto_20240801_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=255)),
                ('email', models.EmailField(default='as@gmail.com', max_length=254)),
                ('contact', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=15)),
            ],
        ),
    ]
