# Generated by Django 3.2.12 on 2024-08-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendapp', '0003_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='gender',
            field=models.CharField(default='', max_length=255),
        ),
    ]
