# Generated by Django 4.1.13 on 2024-08-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendapp', '0006_alter_teachers_options_alter_teachers_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='teachers',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
